version: '3.8'

services:
  postgres:
    image: postgres:13.3-alpine
    container_name: postgress-container
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres_db
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql